import Head from "next/head";
import { DATABASE_ID, TOKEN } from "@/config";
import HelloToday from "@/components/HelloToday";
import Loading from "@/components/Loading";
export default function Home() {
  return (
    <>
      <Head>
        <title>Hello Today's To Do</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Loading />
      <HelloToday />
    </>
  );
}

// branch test :)

// 빌드 타임에 호출
// export async function getStaticProps() {
//   const options = {
//     method: "POST",
//     headers: {
//       Accept: "application/json",
//       "Notion-Version": "2022-06-28",
//       "Content-Type": "application/json",
//       Authorization: `${TOKEN}`,
//     },
//     body: JSON.stringify({ page_size: 100 }),
//   };
//   const response = await fetch(`https://api.notion.com/v1/databases/${DATABASE_ID}/query`, options);
//   const result = await response.json();
//   console.log(result);
//   return {
//     props: {}, // will be passed to the page component as props
//   };
// }
